
import { Sale } from './types';

export const MOCK_SALES_DATA: Sale[] = [
  { 
    id: 1, 
    dataCadastro: '2023-10-01', 
    unidade: 'São Paulo', 
    vendedor: 'Ana Silva', 
    nomeCliente: 'Carlos Pereira', 
    telefone: '(11) 98765-4321', 
    categoria: 'Produto A', 
    etapaFunil: 'Fechamento', 
    origem: 'Website', 
    status: 'Ativo', 
    valorInicial: 1400, 
    valorVenda: 1500.00,
    qualificacao: 4,
    cidade: 'São Paulo',
    endereco: 'Av. Paulista, 1000',
    email: 'carlos@email.com'
  },
  { 
    id: 2, 
    dataCadastro: '2023-10-02', 
    unidade: 'Rio de Janeiro', 
    vendedor: 'Bruno Costa', 
    nomeCliente: 'Mariana Lima', 
    telefone: '(21) 91234-5678', 
    categoria: 'Serviço X', 
    etapaFunil: 'Negociação', 
    origem: 'Indicação', 
    status: 'Ativo', 
    valorInicial: 3000, 
    valorVenda: 3200.50,
    qualificacao: 3,
    cidade: 'Rio de Janeiro',
    email: 'mariana@email.com'
  },
  { 
    id: 3, 
    dataCadastro: '2023-10-03', 
    unidade: 'Belo Horizonte', 
    vendedor: 'Cláudia Martins', 
    nomeCliente: 'Rafael Oliveira', 
    telefone: '(31) 95555-8888', 
    categoria: 'Produto B', 
    etapaFunil: 'Prospecção', 
    origem: 'Feira', 
    status: 'Ativo', 
    valorInicial: 750, 
    valorVenda: 800.00,
    qualificacao: 2
  },
  { 
    id: 4, 
    dataCadastro: '2023-10-04', 
    unidade: 'São Paulo', 
    vendedor: 'Ana Silva', 
    nomeCliente: 'Fernanda Souza', 
    telefone: '(11) 99999-1111', 
    categoria: 'Serviço Y', 
    etapaFunil: 'Lead', 
    origem: 'Anúncio', 
    status: 'Ativo', 
    valorInicial: 4800, 
    valorVenda: 5000.00,
    qualificacao: 5
  },
  { 
    id: 5, 
    dataCadastro: '2023-10-05', 
    unidade: 'Porto Alegre', 
    vendedor: 'Daniel Almeida', 
    nomeCliente: 'Juliana Ferreira', 
    telefone: '(51) 98888-2222', 
    categoria: 'Produto A', 
    etapaFunil: 'Fechamento', 
    origem: 'Website', 
    status: 'Fechado', 
    valorInicial: 1400, 
    valorVenda: 1450.75,
    qualificacao: 4
  },
  { 
    id: 6, 
    dataCadastro: '2023-10-06', 
    unidade: 'Rio de Janeiro', 
    vendedor: 'Bruno Costa', 
    nomeCliente: 'Lucas Gomes', 
    telefone: '(21) 97777-3333', 
    categoria: 'Produto B', 
    etapaFunil: 'Negociação', 
    origem: 'Indicação', 
    status: 'Ativo', 
    valorInicial: 900, 
    valorVenda: 950.00 
  },
  { 
    id: 7, 
    dataCadastro: '2023-10-07', 
    unidade: 'São Paulo', 
    vendedor: 'Ana Silva', 
    nomeCliente: 'Patrícia Rocha', 
    telefone: '(11) 96666-4444', 
    categoria: 'Serviço X', 
    etapaFunil: 'Perdido', 
    origem: 'Website', 
    status: 'Perdido', 
    valorInicial: 2800, 
    valorVenda: 2800.00 
  },
  { 
    id: 8, 
    dataCadastro: '2023-10-08', 
    unidade: 'Belo Horizonte', 
    vendedor: 'Cláudia Martins', 
    nomeCliente: 'Ricardo Santos', 
    telefone: '(31) 95555-4444', 
    categoria: 'Serviço Y', 
    etapaFunil: 'Prospecção', 
    origem: 'Feira', 
    status: 'Ativo', 
    valorInicial: 4200, 
    valorVenda: 4500.00 
  },
  { 
    id: 9, 
    dataCadastro: '2023-10-09', 
    unidade: 'Porto Alegre', 
    vendedor: 'Daniel Almeida', 
    nomeCliente: 'Sandra Alves', 
    telefone: '(51) 94444-5555', 
    categoria: 'Produto A', 
    etapaFunil: 'Lead', 
    origem: 'Anúncio', 
    status: 'Ativo', 
    valorInicial: 1100, 
    valorVenda: 1200.00 
  },
  { 
    id: 10, 
    dataCadastro: '2023-10-10', 
    unidade: 'São Paulo', 
    vendedor: 'Ana Silva', 
    nomeCliente: 'Vinícius Dias', 
    telefone: '(11) 93333-6666', 
    categoria: 'Produto B', 
    etapaFunil: 'Fechamento', 
    origem: 'Website', 
    status: 'Fechado', 
    valorInicial: 700, 
    valorVenda: 750.25 
  },
  { 
    id: 11, 
    dataCadastro: '2023-10-11', 
    unidade: 'Curitiba', 
    vendedor: 'Eduardo Lima', 
    nomeCliente: 'Beatriz Costa', 
    telefone: '(41) 92222-7777', 
    categoria: 'Serviço X', 
    etapaFunil: 'Negociação', 
    origem: 'Indicação', 
    status: 'Ativo', 
    valorInicial: 3000, 
    valorVenda: 3100.00 
  },
  { 
    id: 12, 
    dataCadastro: '2023-10-12', 
    unidade: 'Curitiba', 
    vendedor: 'Eduardo Lima', 
    nomeCliente: 'André Mendes', 
    telefone: '(41) 91111-8888', 
    categoria: 'Produto A', 
    etapaFunil: 'Prospecção', 
    origem: 'Anúncio', 
    status: 'Ativo', 
    valorInicial: 1750, 
    valorVenda: 1800.00 
  },
];
